language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
services:
  - mongodb
deploy:
  provider: openshift
  user: "hulehule20"
  password: "Marc112009" # can be encrypted
  domain: "hulehule20"